

on: 
  pull_request:
  push:
    branches: [main, beta]

jobs:
  run-tests: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - run: npm ci    
    - run: npm run test

  run-compile:
    name: Expect code to be able to compile successfully 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - run: npm ci    
    - run: npm run compile 

  run-cli:
    name: Run the CLI, expect no errors 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - run: npm ci    
    - run: npm run compile 
    - run: npm pack 
    - run: npm install --no-save is-it-deployed-1.0.0.tgz
    - run: node node_modules/.bin/is-it-deployed --package-manager npm --package-name react --package-version 18.0.0
